# Generated by Django 2.2 on 2019-10-10 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type',
            old_name='name',
            new_name='type',
        ),
    ]
