# Generated by Django 2.2 on 2019-10-11 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20191011_0920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracker',
            old_name='Project',
            new_name='project',
        ),
    ]
